---
title: "Summary of occurrences"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---



```{r load data, message=FALSE, warning=FALSE, include=FALSE}

library(gsheet)
library(tidyverse)
library(crosstalk)
library(DT)
library(ggthemes)
library(janitor)
library(cowplot)
library(plotly)

Sys.setlocale("LC_ALL", "pt_BR.UTF-8")


dat1 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1_FKOEwXyNBgc8MnzMVoQvFsl1Llae_VGNjgj5K0CaH8/edit?usp=sharing")


set.seed(1000)
dat1$lat <- round(jitter(dat1$lat, factor = 1, amount = 0.001), 4)
dat1$lon <- round(jitter(dat1$lon, factor = 1, amount = 0.001), 4)
```

```{r all table, echo=FALSE}
dat_table <- dat1 %>%
  select(family, species_name, lat, lon, state, municipality, biome, author_record, year_record)
sd <- SharedData$new(dat_table)
```

The total number of records in the database is `r nrow(dat_table)`.

### Family

```{r echo=FALSE}
library(janitor)
dat_table %>%
  tabyl(family) %>% 
  ggplot(aes(reorder(family, n), n))+
  geom_col(fill = "lightblue")+
  geom_text(aes(label = n),
              position = position_stack(vjust = 1.03))+
  coord_flip()+
  theme_minimal_vgrid()+
  labs(x = "", y = "Number of reports")

```

### Biome

```{r echo=FALSE}
library(janitor)
dat_table %>%
  tabyl(biome) %>% 
  ggplot(aes(reorder(biome, n), n))+
  geom_col(fill = "lightblue")+
  geom_text(aes(label = n),
              position = position_stack(vjust = 1.03))+
  coord_flip()+
  theme_minimal_vgrid()+
  labs(x = "", y = "Number of reports")

```

### BR State

```{r echo=FALSE}
library(janitor)
dat_table %>%
  tabyl(state) %>% 
  ggplot(aes(reorder(state, n), n))+
  geom_col(fill = "lightblue")+
  geom_text(aes(label = n),
              position = position_stack(vjust = 1.03))+
  coord_flip()+
  theme_minimal_vgrid()+
  labs(x = "", y = "Number of reports")

```



### Year

```{r echo=FALSE}
library(janitor)
dat_table %>%
  tabyl(year_record) %>% 
  ggplot(aes(year_record, n))+
  geom_col(fill = "lightblue")+
  geom_text(aes(label = n),
              position = position_stack(vjust = 1.05))+
  theme_minimal_hgrid()+
  xlim(2000,2022)+
  labs(x = "", y = "Number of reports")

```

### Latitude

```{r echo=FALSE}
library(janitor)
dat_table %>%
  tabyl(lat) %>% 
  ggplot(aes(lat))+
geom_histogram(fill = "lightblue", color = "white")+
  theme_minimal_hgrid()+
  labs(x = "Latitude", y = "Number of reports")

```


### Longitude

```{r echo=FALSE}
library(janitor)
dat_table %>%
  tabyl(lon) %>% 
  ggplot(aes(lon))+
geom_histogram(fill = "lightblue", color = "white")+
  theme_minimal_hgrid()+
  labs(x = "Longitude", y = "Number of reports")

```