---
title: "Species distribution data"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3

---


```{r load data, message=FALSE, warning=FALSE, include=FALSE}

library(tidyverse)
library(crosstalk)
library(plotly)
library(viridis)
library(gsheet)
library(leaflet.providers)
library(leaflet)
library(DT)
library(janitor)

Sys.setlocale("LC_ALL", "pt_BR.UTF-8")


dat1 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1_FKOEwXyNBgc8MnzMVoQvFsl1Llae_VGNjgj5K0CaH8/edit?usp=sharing")




set.seed(1000)
dat1$lat <- round(jitter(dat1$lat, factor = 1, amount = 0.001), 4)
dat1$lon <- round(jitter(dat1$lon, factor = 1, amount = 0.001), 4)
```

```{r all table, echo=FALSE}
dat_table <- dat1 %>%
  select(family, genera, species_name, author, lat, lon, state, municipality, biome, author_record, year_record)
sd <- SharedData$new(dat_table)
```


```{r echo=FALSE, layout="l-page"}
library(crosstalk)
bscols(
  filter_slider("year", "Year of record", sd, ~year_record, round = TRUE),
  filter_select("family", "Family", sd, ~family),
   filter_select("Genus", "Genus", sd, ~genera),
   filter_select("Species", "Species", sd, ~species_name),
   filter_select("Biome", "Biome", sd, ~biome))



```




```{r echo=FALSE, layout="l-screen-inset shaded", fig.height=5.2}
library(RColorBrewer)
library(htmltools)

pal <- colorFactor("Set3", domain = c("Baetidae",
"Caenidae",
"Coryphoridae",
"Ephemeridae",
"Euthyplociidae",
"Leptohyphidae",
"Leptophlebiidae",
"Melanemerellidae",
"Oligoneuriidae",
"Polymitarcyidae"))

leaflet(data = sd, width = "100%") %>%
 setView(-46.8, -18.40, zoom = 4) %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  addProviderTiles("OpenTopoMap", group = "Terrain") %>%
  addScaleBar("bottomright") %>%
  addProviderTiles(providers$CartoDB.Voyager, group = "Default") %>%
  addLayersControl(
    baseGroups = c("Default", "Aerial", "Terrain"),
    
    options = layersControlOptions(collapsed = T)
  ) %>%
  addCircleMarkers(
  
    radius = 6,
    fillOpacity = 1,
    weight = 0.5,
    label = paste(dat1$family, "- Details"),
    fillColor = ~ pal(family),
    
    
    popup = paste(
      "<h3>Specimen details</h3>",
      "Family:", dat1$"family", "<br>",
      
      #"Genera:", dat1$"genera", "</i>", "<br>",
       "Species:", dat1$"species_name", "<br>",
      "Author:", dat1$"author", "<br>",
      "Year:", dat1$"year", "<br>",
      "Present today?", dat1$"present_today", "<br>",
        
     
        "Biome:", dat1$"biome", "<br>",
     
      "State:", dat1$"state", "<br>",
      "Municipality:", dat1$"municipality", "<br>",

      "Article titl:", dat1$"title", "<br>",
      "Author:", dat1$"author_record", "<br>",
      "Publication year:", dat1$"year_record", "<br>"
      
    )

  ) %>%
  addLegend("bottomleft",
    pal = pal,
    values = ~family,
    title = "Family",
    opacity = 1
  ) %>% 
  
  addMeasure(
    position = "bottomleft",
    primaryLengthUnit = "meters",
    primaryAreaUnit = "sqmeters",
    activeColor = "#3D535D",
    completedColor = "#7D4479") %>% 
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 4",
    onClick=JS("function(btn, map){ map.setZoom(4); }"))) 
```



